name: arxiv_survey

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * * #JST 10:00

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv

      - name: Run arxiv_survey.py
        run: |
          python arxiv_survey.py

      - name: Commit and Push
        run: |
          echo commit and push
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.USER_NAME }}
          git add README.md
          git commit -m "Update"
          git pull origin main
          git push origin main
